review-branch
ashmalzahra/project-code-review pull request #1
Opened 2023-01-24 19:45 UTC by ashmalzahra

Please review code.

2023-01-24 20:32 UTC, anderCM requested changes
# Highlights!
- Good feature branch name ✔️
- Descriptive pull request ✔️
- Descriptive commit messages ✔️
- Good code organization and working app ✔️
# Status: Required Changes ♻️⛔️
Check the comments under the review.

2023-01-24 20:32 UTC, anderCM commented on index.js
> +  window.location.reload();
Please Kindly avoid using `window` to reach the `location` method, You can use `location` directly like this: `location.reload();`

2023-01-24 20:32 UTC, anderCM commented on index.js
> +});
According to `KISS` rules, get all the `task` classes from the `DOM` just to select one of them is not a good practice. So please kindly add an `id`, a `name` or another way to identify this element get only this element to apply the `eventListener`

2023-01-24 20:32 UTC, anderCM commented on index.js
> +  window.location.reload();
Please Kindly avoid using `window` to reach the `location` method, You can use `location` directly like this: `location.reload();`

2023-03-25 09:07 UTC, ashmalzahra commented
Thank you!

2023-03-25 09:08 UTC, merged

2023-04-04 21:01 UTC, anderCM reviewed
# Highlights!
Good feature branch name ✔️
Descriptive pull request ✔️
Descriptive commit messages ✔️
Good code organization and working app ✔️

# Status: Approbed ♻️🎉🎉

Hi @ashmalzahra , your project is complete. There is nothing else to say than merge it!

2023-04-05 15:22 UTC, ashmalzahra commented
Thank you! :memo: